package com.parameta.service.empleados.srv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2021-03-15T22:26:13.735-05:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "SrvGuardarEmpleadosPortService",
                  wsdlLocation = "file:/F:/Desarrollo/Workspeaces/Pruebas%20técnicas/empleados-service-client/src/main/resources/empleados.wsdl",
                  targetNamespace = "http://www.parameta.com/service/empleados")
public class SrvGuardarEmpleadosPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.parameta.com/service/empleados", "SrvGuardarEmpleadosPortService");
    public final static QName SrvGuardarEmpleadosPortSoap11 = new QName("http://www.parameta.com/service/empleados", "SrvGuardarEmpleadosPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/Desarrollo/Workspeaces/Pruebas%20técnicas/empleados-service-client/src/main/resources/empleados.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SrvGuardarEmpleadosPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/F:/Desarrollo/Workspeaces/Pruebas%20técnicas/empleados-service-client/src/main/resources/empleados.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SrvGuardarEmpleadosPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SrvGuardarEmpleadosPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SrvGuardarEmpleadosPortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SrvGuardarEmpleadosPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SrvGuardarEmpleadosPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SrvGuardarEmpleadosPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SrvGuardarEmpleadosPort
     */
    @WebEndpoint(name = "SrvGuardarEmpleadosPortSoap11")
    public SrvGuardarEmpleadosPort getSrvGuardarEmpleadosPortSoap11() {
        return super.getPort(SrvGuardarEmpleadosPortSoap11, SrvGuardarEmpleadosPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SrvGuardarEmpleadosPort
     */
    @WebEndpoint(name = "SrvGuardarEmpleadosPortSoap11")
    public SrvGuardarEmpleadosPort getSrvGuardarEmpleadosPortSoap11(WebServiceFeature... features) {
        return super.getPort(SrvGuardarEmpleadosPortSoap11, SrvGuardarEmpleadosPort.class, features);
    }

}
